### ISSUE TITLE
Photoshop to Base64 PNG 

### ISSUE THREAD

**Issue by fEyebrow** [nvkzNemo/UberFaces#1]
hello nvkzNemo,
I watched your video about transforming the artlayer of photoshop to Base64 PNG in youtube.
I really want to know how you did it .
I read the photoshop-cc-javascript-ref-2015 and didn't find any property or method to get the data of layer. 
Can you help me, thanks?

**Comment by anton-liubushkin** [comment]
Hi, @FourEyebrowXiake 

Look at [this gist](https://gist.github.com/nvkzNemo/470cd046f785e32e2aa964f2a7091a62)

**Comment by fEyebrow** [comment]
`  pngPath = new File(Folder.temp + "/" + layerID).fsName;`
what is layerID?

my Folder.temp is empty. 
![image](https://user-images.githubusercontent.com/18180417/41152867-8c3a885a-6b47-11e8-9a1c-9fc38fd00f93.png)

@nvkzNemo

**Comment by anton-liubushkin** [comment]
@FourEyebrowXiake 

**Folder.temp** is default Photoshop variable. You need to run this code in Ps with **File > Scripts > Browse...**. 

You can get the **layerID** with `layerID = app.activeDocument.activeLayer.id;` or another way. Also you can put your own file name in that gist.

**Comment by fEyebrow** [comment]
hi @nvkzNemo,
I can successfully export small images,but when I exported a big image, ps was stuck. Do you have this kind of problem？
this is my code:
```
  getLayerInfo:function (lay) {
    var pngPath, pngFile, pngData64
    var doc =  app.activeDocument
    doc.activeLayer = lay
    pngPath = new File(Folder.temp + "/" + doc.activeLayer.id).fsName;
    this.writeSelectedLayerPNGfile(pngPath)
    pngFile = new File(pngPath + ".base64");
    pngFile.open('r');
    pngFile.encoding = "UTF-8";
    pngData64 = pngFile.read();
    pngFile.close();
    pngFile.remove();
      var result = {
        image: pngData64,
        position: [lay.bounds[0].value, lay.bounds[1].value],
        tag: lay.name,
        shape:[lay.bounds[2].value-lay.bounds[0].value,lay.bounds[3].value-lay.bounds[1].value]
      }
    return JSON.stringify(result)
  },
```

**Comment by fEyebrow** [comment]
I solved this
